CREATE OR REPLACE PROCEDURE actualizar_valor_producto (
    p_codigoproducto IN JPALACIO_PRODUCTOS.CODIGOPRODUCTO%TYPE,
    p_nuevo_precio IN JPALACIO_PRODUCTOS.PRECIOVENTA%TYPE
) AS
BEGIN
    UPDATE JPALACIO_PRODUCTOS
    SET PRECIOVENTA = p_nuevo_precio
    WHERE CODIGOPRODUCTO = p_codigoproducto;
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE actualizar_inventario_producto (
    p_codigoproducto IN JPALACIO_PRODUCTOS.CODIGOPRODUCTO%TYPE,
    p_nueva_cantidad IN JPALACIO_PRODUCTOS.CANTIDADENSTOCK%TYPE
) AS
BEGIN
    UPDATE JPALACIO_PRODUCTOS
    SET CANTIDADENSTOCK = p_nueva_cantidad
    WHERE CODIGOPRODUCTO = p_codigoproducto;
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE insertar_detalle_pedido (
    p_codigopedido IN JPALACIO_DETALLEPEDIDOS.CODIGOPEDIDO%TYPE,
    p_codigoproducto IN JPALACIO_DETALLEPEDIDOS.CODIGOPRODUCTO%TYPE,
    p_cantidad IN JPALACIO_DETALLEPEDIDOS.CANTIDAD%TYPE,
    p_precio_unidad IN JPALACIO_DETALLEPEDIDOS.PRECIOUNIDAD%TYPE,
    p_numerolinea IN JPALACIO_DETALLEPEDIDOS.NUMEROLINEA%TYPE
) AS
BEGIN
    INSERT INTO JPALACIO_DETALLEPEDIDOS (CODIGOPEDIDO, CODIGOPRODUCTO, CANTIDAD, PRECIOUNIDAD, NUMEROLINEA)
    VALUES (p_codigopedido, p_codigoproducto, p_cantidad, p_precio_unidad, p_numerolinea);
    COMMIT;
END;
/
CREATE OR REPLACE FUNCTION valor_producto_mas_vendido RETURN NUMBER IS
    v_valor_producto NUMBER;
BEGIN
    SELECT MAX(PRECIOUNIDAD * CANTIDAD)
    INTO v_valor_producto
    FROM JPALACIO_DETALLEPEDIDOS;

    RETURN v_valor_producto;
END;
/
CREATE OR REPLACE FUNCTION gama_producto_mas_vendido RETURN VARCHAR2 IS
    v_gama JPALACIO_PRODUCTOS.GAMA%TYPE;
BEGIN
    SELECT GAMA
    INTO v_gama
    FROM JPALACIO_PRODUCTOS
    WHERE CODIGOPRODUCTO = (
        SELECT CODIGOPRODUCTO
        FROM JPALACIO_DETALLEPEDIDOS
        GROUP BY CODIGOPRODUCTO
        ORDER BY SUM(CANTIDAD) DESC
        FETCH FIRST 1 ROW ONLY
    );

    RETURN v_gama;
END;
/
CREATE OR REPLACE PROCEDURE registrar_medio_pago (
    p_codigocliente IN JPALACIO_PAGOS.CODIGOCLIENTE%TYPE,
    p_formapago IN JPALACIO_PAGOS.FORMAPAGO%TYPE,
    p_idtransaccion IN JPALACIO_PAGOS.IDTRANSACCION%TYPE,
    p_fechapago IN JPALACIO_PAGOS.FECHAPAGO%TYPE,
    p_cantidad IN JPALACIO_PAGOS.CANTIDAD%TYPE
) AS
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM JPALACIO_CLIENTES
        WHERE CODIGOCLIENTE = p_codigocliente
    ) THEN
        RAISE_APPLICATION_ERROR(-20001, 'El cliente no existe');
    END IF;

    INSERT INTO JPALACIO_PAGOS (CODIGOCLIENTE, FORMAPAGO, IDTRANSACCION, FECHAPAGO, CANTIDAD)
    VALUES (p_codigocliente, p_formapago, p_idtransaccion, p_fechapago, p_cantidad);
END;
/
CREATE OR REPLACE TRIGGER descontar_existencias
AFTER INSERT ON JPALACIO_DETALLEPEDIDOS
FOR EACH ROW
BEGIN
    UPDATE JPALACIO_PRODUCTOS
    SET CANTIDADENSTOCK = CANTIDADENSTOCK - :NEW.CANTIDAD
    WHERE CODIGOPRODUCTO = :NEW.CODIGOPRODUCTO;
    COMMIT;
END;
/
CREATE OR REPLACE TRIGGER evitar_autojefatura
BEFORE INSERT OR UPDATE ON JPALACIO_EMPLEADOS
FOR EACH ROW
BEGIN
    IF :NEW.CODIGOEMPLEADO = :NEW.CODIGOJEFE THEN
        RAISE_APPLICATION_ERROR(-20002, 'Un empleado no puede ser su propio jefe');
    END IF;
END;
/
CREATE TABLE JPALACIO_AUDITORIA_CLIENTES (
    ID NUMBER PRIMARY KEY,
    OPERACION VARCHAR2(10 BYTE),
    FECHA DATE,
    USUARIO VARCHAR2(50 BYTE),
    DETALLES CLOB
);

CREATE TABLE JPALACIO_AUDITORIA_PEDIDOS (
    ID NUMBER PRIMARY KEY,
    OPERACION VARCHAR2(10 BYTE),
    FECHA DATE,
    USUARIO VARCHAR2(50 BYTE),
    DETALLES CLOB
);
CREATE SEQUENCE JPALACIO_AUDITORIA_CLIENTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE JPALACIO_AUDITORIA_PEDIDOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER auditar_clientes
AFTER INSERT ON JPALACIO_CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO JPALACIO_AUDITORIA_CLIENTES (ID, OPERACION, FECHA, DETALLES)
    VALUES (
        JPALACIO_AUDITORIA_CLIENTES_SEQ.NEXTVAL,
        'INSERT',
        SYSDATE,
		'Insert details...'
    );
END;
/

CREATE OR REPLACE TRIGGER auditar_clientes_update
AFTER UPDATE ON JPALACIO_CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO JPALACIO_AUDITORIA_CLIENTES (ID, OPERACION, FECHA,DETALLES)
    VALUES (
        JPALACIO_AUDITORIA_CLIENTES_SEQ.NEXTVAL,
        'UPDATE',
        SYSDATE,
		'UPDATE details...'
    );
END;
/
CREATE OR REPLACE TRIGGER auditar_clientes_delete
AFTER UPDATE ON JPALACIO_CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO JPALACIO_AUDITORIA_CLIENTES (ID, OPERACION, FECHA,DETALLES)
    VALUES (
        JPALACIO_AUDITORIA_CLIENTES_SEQ.NEXTVAL,
        'DELETE',
        SYSDATE,
		'DELETE details...'
    );
END;
/
CREATE OR REPLACE TRIGGER auditar_pedidos
AFTER INSERT ON JPALACIO_CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO JPALACIO_AUDITORIA_CLIENTES (ID, OPERACION, FECHA, DETALLES)
    VALUES (
        JPALACIO_AUDITORIA_CLIENTES_SEQ.NEXTVAL,
        'INSERT',
        SYSDATE,
		'Insert details...'
    );
END;
/
CREATE OR REPLACE TRIGGER auditar_pedidos_update
AFTER INSERT ON JPALACIO_CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO JPALACIO_AUDITORIA_CLIENTES (ID, OPERACION, FECHA, DETALLES)
    VALUES (
        JPALACIO_AUDITORIA_CLIENTES_SEQ.NEXTVAL,
        'UPDATE',
        SYSDATE,
		'UPDATE details...'
    );
END;
/
CREATE OR REPLACE TRIGGER auditar_pedidos_delete
AFTER INSERT ON JPALACIO_CLIENTES
FOR EACH ROW
BEGIN
    INSERT INTO JPALACIO_AUDITORIA_CLIENTES (ID, OPERACION, FECHA, DETALLES)
    VALUES (
        JPALACIO_AUDITORIA_CLIENTES_SEQ.NEXTVAL,
        'DELETE',
        SYSDATE,
		'DELETE details...'
    );
END;
/
ALTER TABLE JPALACIO_PEDIDOS ADD (VALORTOTAL NUMBER(15, 2));
/
CREATE OR REPLACE PROCEDURE actualizar_valor_total_pedido (
    p_codigopedido IN JPALACIO_PEDIDOS.CODIGOPEDIDO%TYPE
) AS
    v_valor_total NUMBER;
BEGIN
    SELECT SUM(CANTIDAD * PRECIOUNIDAD)
    INTO v_valor_total
    FROM JPALACIO_DETALLEPEDIDOS
    WHERE CODIGOPEDIDO = p_codigopedido;

    UPDATE JPALACIO_PEDIDOS
    SET VALORTOTAL = v_valor_total
    WHERE CODIGOPEDIDO = p_codigopedido;
    COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE actualizar_valor_total_todos_pedidos AS
BEGIN
    FOR r IN (SELECT CODIGOPEDIDO FROM JPALACIO_PEDIDOS) LOOP
        actualizar_valor_total_pedido(r.CODIGOPEDIDO);
    END LOOP;
END;
/
CREATE OR REPLACE TRIGGER actualizar_valor_total
AFTER INSERT OR UPDATE OR DELETE ON JPALACIO_DETALLEPEDIDOS
FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN
        actualizar_valor_total_pedido(:NEW.CODIGOPEDIDO);
    ELSIF DELETING THEN
        actualizar_valor_total_pedido(:OLD.CODIGOPEDIDO);
    END IF;
END;
/
CREATE OR REPLACE TRIGGER verificar_precio_venta
BEFORE INSERT OR UPDATE ON JPALACIO_PRODUCTOS
FOR EACH ROW
BEGIN
    IF :NEW.PRECIOVENTA < :NEW.PRECIOPROVEEDOR * 1.1 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El precio de venta debe ser superior en un 10% al precio del proveedor');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER verificar_inventario
BEFORE INSERT OR UPDATE ON JPALACIO_DETALLEPEDIDOS
FOR EACH ROW
DECLARE
    v_cantidad_en_stock NUMBER;
BEGIN
    SELECT CANTIDADENSTOCK INTO v_cantidad_en_stock
    FROM JPALACIO_PRODUCTOS
    WHERE CODIGOPRODUCTO = :NEW.CODIGOPRODUCTO;

    IF v_cantidad_en_stock - :NEW.CANTIDAD < 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'No hay suficiente inventario para realizar el pedido');
    END IF;
END;
/
ALTER TABLE JPALACIO_GAMASPRODUCTOS ADD (DESCUENTO NUMBER(5, 2));
/
CREATE OR REPLACE TRIGGER aplicar_descuento
AFTER INSERT OR UPDATE ON JPALACIO_DETALLEPEDIDOS
FOR EACH ROW
DECLARE
    v_descuento NUMBER;
BEGIN
    SELECT DESCUENTO INTO v_descuento
    FROM JPALACIO_GAMASPRODUCTOS
    WHERE GAMA = (SELECT GAMA FROM JPALACIO_PRODUCTOS WHERE CODIGOPRODUCTO = :NEW.CODIGOPRODUCTO);

    IF v_descuento IS NOT NULL THEN
        UPDATE JPALACIO_DETALLEPEDIDOS
        SET PRECIOUNIDAD = PRECIOUNIDAD * (1 - v_descuento / 100)
        WHERE CODIGOPEDIDO = :NEW.CODIGOPEDIDO AND CODIGOPRODUCTO = :NEW.CODIGOPRODUCTO;
        COMMIT;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER verificar_cantidad_inventario
BEFORE INSERT OR UPDATE ON JPALACIO_DETALLEPEDIDOS
FOR EACH ROW
DECLARE
    v_cantidad_en_stock NUMBER;
BEGIN
    SELECT CANTIDADENSTOCK INTO v_cantidad_en_stock
    FROM JPALACIO_PRODUCTOS
    WHERE CODIGOPRODUCTO = :NEW.CODIGOPRODUCTO;

    IF :NEW.CANTIDAD > v_cantidad_en_stock THEN
        RAISE_APPLICATION_ERROR(-20005, 'La cantidad solicitada excede la cantidad disponible en el inventario');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER actualizar_inventario
AFTER INSERT ON JPALACIO_DETALLEPEDIDOS
FOR EACH ROW
BEGIN
    UPDATE JPALACIO_PRODUCTOS
    SET CANTIDADENSTOCK = CANTIDADENSTOCK - :NEW.CANTIDAD
    WHERE CODIGOPRODUCTO = :NEW.CODIGOPRODUCTO;
    COMMIT;
END;
/
CREATE SEQUENCE JPALACIO_NOTIFICACIONES_SEQ START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER notificar_limite_credito
AFTER INSERT ON JPALACIO_PAGOS
FOR EACH ROW
DECLARE
    v_limite_credito NUMBER;
    v_total_pagado NUMBER;
BEGIN
    SELECT LIMITECREDITO INTO v_limite_credito
    FROM JPALACIO_CLIENTES
    WHERE CODIGOCLIENTE = :NEW.CODIGOCLIENTE;

    SELECT SUM(CANTIDAD) INTO v_total_pagado
    FROM JPALACIO_PAGOS
    WHERE CODIGOCLIENTE = :NEW.CODIGOCLIENTE;

    IF v_total_pagado > v_limite_credito THEN
        INSERT INTO JPALACIO_NOTIFICACIONES (ID, FECHA, DESTINATARIO, MENSAJE)
        VALUES (
            JPALACIO_NOTIFICACIONES_SEQ.NEXTVAL,
            SYSDATE,
            (SELECT CODIGOEMPLEADOREPRESENTANTE FROM JPALACIO_CLIENTES WHERE CODIGOCLIENTE = :NEW.CODIGOCLIENTE),
            'Ha superado el límite de crédito'
        );
    END IF;
END;
/






















 










